name: Build All Flavors APK

on:
  push:
    branches:
      - "main"
      - "nitaStaging" # Trigger on pushes to the nitaStaging branch
    pull_request:
      branches:
        - "main"
        - "nitaStaging"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      # --- Build each flavor ---
      - name: Build nitaStaging Release APK
        run: ./gradlew assembleNitaStagingRelease


      # --- Upload artifacts ---
      - name: Upload nitaStaging APK
        uses: actions/upload-artifact@v4
        with:
          name: nitaStaging-apk
          path: app/build/outputs/apk/nitaStaging/release/*.apk

